### ISSUE TITLE
Git tag 4.0.0 is identical to 3.0.4

### ISSUE THREAD

**Issue by cweiske** [CDRO/simulatebe#14]
The git tag "4.0.0" is the same code as tag "3.0.4", and is totally different from the code for 4.0.0 in TER: https://extensions.typo3.org/extension/download/simulatebe/4.0.0/zip

Also, the repository has a tag 9.5.9 which is code-wise before 9.5.0, since 9.5.0 is the merge of the 9.5.9 patch.

**Comment by CDRO** [comment]
Thanks for pointing it out. The 9.5.9 tag was removed, as it was indeed wrong.

**Comment by cweiske** [comment]
So what about the tag v4, which is different from the 4.0.0 code in TER?

**Comment by CDRO** [comment]
I'll update the tag to point to 9.5.0, as this is what is in TER as well, as soon as I'm able to clone this project again.

I'll also release a maintenance release (which was meant to be released at the beginning of February) for TYPO3 9.
