### ISSUE TITLE
Duplicated Git-repository and Issue tracking

### ISSUE THREAD

**Issue by markuspoerschke** [CDRO/simulatebe#7]
It seems like there are two active issue tracking systems and two active Git repositories for this project.

Active Git repositories:
* https://github.com/CDRO/simulatebe
* https://forge.typo3.org/projects/extension-simulatebe/repository

Active issue trackers:
* https://github.com/CDRO/simulatebe/issues
* https://forge.typo3.org/projects/extension-simulatebe/issues

Both are linked on the extension page in TER: https://extensions.typo3.org/extension/simulatebe/

Which one is the official one? I recommend to drop forge and move completely to GitHub.

Why is this a problem? There are some changes that have been made to Git in Forge, but they never were applied to the TER version: https://forge.typo3.org/projects/extension-simulatebe/repository/revisions/7e731a46aaec1311b042177d5141d77803d45ec7

I also created an issue in Forge: https://forge.typo3.org/issues/87791

**Comment by cweiske** [comment]
The forge issue tracker and repository seems to be gone:

> https://forge.typo3.org/projects/extension-simulatebe
> 403
> The project you're trying to access has been archived.

**Comment by CDRO** [comment]
I guess, TYPO3 has decided to close the extension forge projects.

I'll close the issue for now.
